#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - nginx

runcmd:
  - cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  - wget https://aws-codedeploy-ap-northeast-1.s3.amazonaws.com/latest/install
  - ruby ./install auto
  - service nginx start
  - chkconfig nginx on
